<?php require ("templates/cabecera.phtml")?>
<?php require ("templates/barra.phtml")?>


<form action="form-update-marca/<?= $marca->id ?>" method="post" id="form-carga-marcas">
      <label for="">Nombre:</label>
      <input type="text" name="nombre"  value="<?= $marca->nombre ?>" id="input-nombre-marca">
      
      <label for="">Origen:</label>
      <input type="text" name="origen" value="<?= $marca->origen ?>" id="input-origen">
      
      <label>Año Fundación:</label>
      <input type="number" name="año_fundacion" value="<?= $marca->año_fundacion ?>" id="input-año">
      
      <label>Cant Empleados:</label>
      <input type="number" name="cant_empleados" value="<?= $marca->cant_empleados ?>" id="input-cant-empleados">
      
      <label>Produccion Anual:</label>
      <input type="number" name="produccion_anual" value="<?= $marca->produccion_anual ?>" id="input-prod-anual">
      
      <label>Facturacion Anual USD:</label>
      <input type="number" name="facturacion_M_USD" value="<?= $marca->facturacion_M_USD ?>" id="input-fact-anual">

      <input type="submit" value="Modificar Marca" id="btn-marcas">
</form>

